/**
 * Excel column -> canonical field map for the Spare Master importer.
 *
 * This file is the versioning seam. When a future export renames a column, add
 * the new header to that field's `aliases` and nothing else in the importer
 * changes. Aliases are matched case-insensitively with whitespace collapsed, so
 * "Parts Number", "PARTSNUMBER " and "parts number" all reach the same field.
 *
 * `canonical` names are the importer's own vocabulary, not schema paths — the
 * transformer decides where each one lands, because several of them (the price
 * columns, the equipment columns) collapse into one nested schema structure.
 */

const normalizeHeader = (header) =>
  String(header ?? "")
    .trim()
    .toUpperCase()
    .replace(/\s+/g, " ");

const SPARE_MASTER_COLUMNS = {
  // The manufacturer's part number. The master's own uniqueID is generated by the
  // application and deliberately has no column here.
  partNumber: { aliases: ["PartsNumber", "Parts Number", "Part No"], required: true },
  partName: { aliases: ["PartsName", "Part Name"], required: true },
  partModel: { aliases: ["PartsModel", "Part Model"] },
  partGroup: { aliases: ["PartsGroup", "Part Group"] },
  maker: { aliases: ["MakerName", "Maker Name", "Maker"] },
  supplierName: { aliases: ["SupplierName", "Supplier Name", "Supplier"] },
  // UnitName carries the readable unit ("EACH"); "Unit" is the numeric code ("01").
  unit: { aliases: ["UnitName", "Unit Name"] },
  registerSection: { aliases: ["SectionName", "Section Name"] },
  leadTime: { aliases: ["LeadTime", "Lead Time"], type: "number" },
  minQuantity: { aliases: ["MinOrder", "Min Order"], type: "number" },
  maxQuantity: { aliases: ["MaxStock", "Max Stock"], type: "number" },

  // Collapsed into costDetails[0] by the transformer.
  stockQuantity: { aliases: ["Quantity1", "Quantity"], type: "number" },
  unitPrice: { aliases: ["UnitPrice1", "Unit Price"], type: "number" },
  unitPriceInINR: { aliases: ["UnitPrice in INR", "UnitPriceInINR"], type: "number" },
  currencyUnit: { aliases: ["CurrencyUnit", "Currency Unit"] },
  currencyRate: { aliases: ["CurrencyRate", "Currency Rate"], type: "number" },

  // Collapsed into the machine + hierarchy blocks by the reference resolver.
  machineName: { aliases: ["MachineName", "Machine Name"] },
  equipment1: { aliases: ["Equipment1", "Equipment 1"] },
  equipment2: { aliases: ["Equipment2", "Equipment 2"] },
  equipment3: { aliases: ["Equipment3", "Equipment 3"] },

  createDate: { aliases: ["CreateDate", "Create Date"], type: "date" },

  // Stock / ordering policy.
  orderPoint: { aliases: ["OrderPoint", "Order Point"], type: "number" },
  orderQty: { aliases: ["OrderQTY", "Order QTY"], type: "number" },
  orderType: { aliases: ["OrderType", "Order Type"] },
  controlType: { aliases: ["ControlType", "Control Type"] },
  stockTaking: { aliases: ["StockTaking", "Stock Taking"] },
  remarks: { aliases: ["Note", "Remarks"] },

  // Issue history the legacy system recorded before this data was imported.
  lastIssuedDate: { aliases: ["ShippingDate", "Shipping Date"], type: "date" },
  previousIssuedDate: {
    aliases: ["BeforeShippingDate", "Before Shipping Date"],
    type: "date",
  },
  totalIssuedQty: { aliases: ["ShippingTotalQTY1"], type: "number" },
  secondaryTotalIssuedQty: { aliases: ["ShippingTotalQTY2"], type: "number" },

  /**
   * Legacy identifiers and flags. Kept under legacyRef on the master rather than
   * promoted to top-level fields: the codes are the legacy system's own keys for
   * values already imported by name (supplier, maker, unit, section), and the
   * flags are constant across the whole export, so none of them are business
   * fields in their own right — they exist for traceability and for matching on
   * a future re-import.
   */
  supplierCode: { aliases: ["SupplierCode", "Supplier Code"] },
  makerCode: { aliases: ["MakerCode", "Maker Code"] },
  unitCode: { aliases: ["Unit"] },
  currencyCode: { aliases: ["CurrencyCode", "Currency Code"] },
  sectionCode: { aliases: ["SectionCode", "Section Code"] },
  mcSectionCode: { aliases: ["M/C Section"] },
  mcSectionName: { aliases: ["M/C Section Name"] },
  secondaryUnitPrice: { aliases: ["UnitPrice2", "Unit Price 2"], type: "number" },
  drawingYN: { aliases: ["DrawingYN"] },
  drawingPrintYN: { aliases: ["DrawingPrintYN"] },
  drawingPrintQty: { aliases: ["DrawingPrintQTY"], type: "number" },
  subPartsSwitch: { aliases: ["SubPartsSwitch"] },
  changedOn: { aliases: ["ChangeDate", "Change Date"], type: "date" },
};

/**
 * Alias -> canonical, built once at module load. Two fields must never claim the
 * same header, so a collision here is a bug in the map above rather than bad
 * input, and it is worth failing loudly at startup instead of silently letting
 * one field win.
 */
const ALIAS_TO_CANONICAL = new Map();

Object.entries(SPARE_MASTER_COLUMNS).forEach(([canonical, { aliases }]) => {
  aliases.forEach((alias) => {
    const key = normalizeHeader(alias);
    if (ALIAS_TO_CANONICAL.has(key))
      throw new Error(
        `Duplicate Spare Master column alias "${alias}" claimed by both "${ALIAS_TO_CANONICAL.get(key)}" and "${canonical}"`,
      );
    ALIAS_TO_CANONICAL.set(key, canonical);
  });
});

const REQUIRED_CANONICAL_FIELDS = Object.entries(SPARE_MASTER_COLUMNS)
  .filter(([, def]) => def.required)
  .map(([canonical]) => canonical);

/**
 * Turns a sheet's header cells into { canonicalField: columnIndex }.
 * Unknown headers are ignored by design — the legacy export carries ~30 columns
 * that are entirely empty and another handful that are constant, and none of
 * them should be treated as an error.
 */
const buildHeaderIndex = (headerCells = []) => {
  const index = {};
  headerCells.forEach((text, columnIndex) => {
    const canonical = ALIAS_TO_CANONICAL.get(normalizeHeader(text));
    if (canonical && index[canonical] === undefined) index[canonical] = columnIndex;
  });
  return index;
};

const countRecognisedColumns = (headerCells = []) =>
  Object.keys(buildHeaderIndex(headerCells)).length;

module.exports = {
  SPARE_MASTER_COLUMNS,
  REQUIRED_CANONICAL_FIELDS,
  normalizeHeader,
  buildHeaderIndex,
  countRecognisedColumns,
};
